### PR TITLE
Create speakingurl.js

### PR DESCRIPTION
**Pull request by vdanelia**
Romanization of Georgian

### CODE REVIEW

**Comment by redaxmedia** [comment]
You changed every single line, I guess the EOL (end of line) are wrong.

Please use Linux `\r` instead of Windows `\n\r`...

**Comment by vdanelia** [comment]
I edited the file in Notepad ++
What i did incorrectly?

**Comment by redaxmedia** [comment]
Take a look on the Files changed tab at the very top of this pull request. You changed the complete file and not just a single part of it.

http://superuser.com/questions/479756/eol-in-notepad-and-notepad

I guess you're looking for the Notepad++ menu entry "Edit -> EOL Conversion". You can convert to Windows/Linux/Mac EOL there. The current format is displayed in the status bar.

**Comment by vdanelia** [comment]
I can't understand what is happening here ... the file is already in linux format... I just copied it from the speakinguri.js file and pasted here.....

**Pull request closed without merging**
