### PR TITLE
Fix sprockets-rails 3.0

### PR DESCRIPTION
**Pull request by bricesanchez**
Hello, this is a fix to be able to use sprocket-rails 3.0.0.

### CODE REVIEW

**Comment by bricesanchez** [comment]
:up :)

**Comment by pid** [comment]
I will publish a new version by the end of the week. Thanks for the contribution 👍

**Comment by bricesanchez** [comment]
Thanks !

**Comment by parndt** [comment]
:+1:

**Comment by pid** [comment]
sorry for the delay, v8.0.0 is now released
have fun ;-)

**Pull request closed without merging**
