### PR TITLE
burmese language support

### PR DESCRIPTION
**Pull request by lovetostrike**
Let me know if something's missing. Thanks!

### CODE REVIEW

**Comment by lovetostrike** [comment]
Can I know how speakingurl handles cases where the transliteration changes as more diatrics are added? I am assuming I don't have to write every possible combos for each alphabet.
Given:

     'က': 'k',
     'ေ': 'e',
     'ာ': 'aa',
     'ော': 'aw'

Correct Results:

     'က' + 'ေ' = 'ကေ' => 'ke',
     'က' + 'ာ' = 'ကာ' => 'kaa'

Wrong results

     'က' + 'ေ' + 'ာ' = 'ကော' => 'keaa'
     'ကေ' + 'ာ' = 'ကော'  => 'keaa'

These need to match the last case 'ော': 'aw' and become 'kaw'. 

     'က' + 'ေ' + 'ာ' = 'ကော' => 'kaw''

**Comment by pid** [comment]
I think, speakingurl isn't really build with this specific language in mind. 
You already insert a translation-table to your pull request, that's the way it will be handled.
Furthermore I couldn't verify the specific cases – I'm not experienced.
If you can add this correct behavour for the burmese language, pull request are welcome :-)
But please add tests to your pull request, so that future development don't destroy the burmese transliteration support.

**Comment by lovetostrike** [comment]
@pid, I tried to add some logic for lookahead characters that doesn't impact linear languages. It's now working with examples and unit tests.

**Comment by pid** [comment]
awesome :+1: 
released v0.19.0

thanks for contribution :-)

**Comment by lovetostrike** [comment]
Thanks for the project too :)

**Pull request closed without merging**
