### PR TITLE
Add Swedish language

### PR DESCRIPTION
**Pull request by simison**
- [Swedish alphabet](https://en.wikipedia.org/wiki/Swedish_alphabet): _The 29 letters of this alphabet are the modern 26-letter basic Latin alphabet ('A' through 'Z') plus 'Å', 'Ä', and 'Ö', in that order._
- [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) for Swedish is `sv`

### CODE REVIEW

**Comment by simison** [comment]
Oh, sorry I didn't notice my editor cleaned out some empty spaces from your files as well. Do you mind or should I remove those bits from PR?

**Comment by pid** [comment]
@simison pid:
If you run gulp, and you should before a commit/PR to run all tests, the code is beautified.

**Comment by simison** [comment]
Sure, just run `gulp` and pushed changed it made:
```
	modified:   lib/speakingurl.js
	modified:   package.json
	modified:   speakingurl.min.js
	modified:   test/test-lang.js
```

I was just lazy and relying on Travis to do its job. ;-)

**Comment by simison** [comment]
btw I think it would be better if you'd create that minified file just before doing a new release. I feel that pull requests should really just modify source files and nothing else.

**Comment by pid** [comment]
@simison I'm currently on the road... will check it soon, when I'm back at the desk;). Thanks for contribution 👍

**Comment by simison** [comment]
No hurry at all. Warm roads!

**Pull request merged**
