### PR TITLE
Add '[' and ']' to the markchar list 

### PR DESCRIPTION
**Pull request by larube**

### CODE REVIEW

**Comment by pid** [comment]
Hi, 
please take a look at http://tools.ietf.org/html/rfc3986 Page 53
That's the reason I don't want to add any character to the list of markChars.

Please upgrade to v1.0.0; released today and you can solve this with the following code:
```
getSlug('[nodejs]', {
  custom: {
    '[': '[',
    ']': ']'
  }
})
```

**Comment by larube** [comment]
OK, thank you very much for the information.

**Comment by pid** [comment]
I added some sugar...  with v1.1.0 you can add the chars as an array
```
getSlug('[nodejs]', {
    custom: [ '[', ']' ]
  }
})
// Output:    [nodejs]
```

**Comment by larube** [comment]
Perfect, that was what I wanted to do !

**Comment by pid** [comment]
Feel free to give the repository a 'star' :-)

**Pull request closed without merging**
