### PR TITLE
complete Romanian characters; move to main table

### PR DESCRIPTION
**Pull request by mgax**
* some uppercase characters were missing (`Ă`, `Â`, `Î`, `Ș`)
* there is no ambiguity in converting to ascii, so we might as well include everything in the main table

### CODE REVIEW

**Comment by pid** [comment]
can you please translate the symbolmap for romanian?

```
            'en': {
                '∆': 'delta',
                '∞': 'infinity',
                '♥': 'love',
                '&': 'and',
                '|': 'or',
                '<': 'less than',
                '>': 'greater than',
                '∑': 'sum',
                '¤': 'currency'
```

than I could add this to the next release, too

**Comment by mgax** [comment]
Done. I assume the translated versions should also be converted to latin characters, right?

**Comment by pid** [comment]
awesome, will copy&paste it, already merged the first pull request, next release is on the way ;-)

**Comment by mgax** [comment]
Cool! :cake:

**Comment by pid** [comment]
speakingurl v4.0.0 released

thanks :+1:

**Pull request closed without merging**
